### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by Conix96** [jackdijkema/binance_positions#1]
Hey,

I wonder how did you get this endpoint please https://github.com/chopbk/binance-leaderboard-bot/blob/eb592ddb7686728c77769e5c436bfa721787cd75/services/leaderboard/leaderboard-api.js#L124 ?
Thanks a lot !

**Comment by jackdijkema** [comment]
i used "https://backend.copyfuture.me/binance/leaderboard/get-real-time?period=ALL" and filtered through the data. BUT the website seems offline so probably not reliable -- I only did this for educational purposes.

**Comment by Conix96** [comment]
Ok thanks a lot !
